[FCA-10] Implement spinner on main screen
matxowy/FlashcardsApp pull request #5
Opened 2023-03-10 14:58 UTC by matxowy

- Implemented spinner on main screen
- Implemented displaying correct category name and flashcard text
- Added default category and flashcard to database when open app for the first time
- Added insert, update and delete methods to daos
- Added coroutine extension
- Added circular progress indicator to learning screen
- Added correct navigation to learning screen
- Some code improvements

2023-03-13 17:04 UTC, msniezek-Sii requested changes
Zostawiłem trochę uwag, część to tylko uwagi a część trzeba zmienić :) 
Poza tym nie wiem trochę dlaczego stworzyłeś repozytorium dla każdego ekranu. Repozytoria są bardziej dla źródeł danych np `DatabaseRepository`, `RequestRepository`, `PreferencesRepository` itd. Masz może jakiś artykuł albo coś, gdzie jest uzasadniony taki podział?

2023-03-13 17:04 UTC, msniezek-Sii commented on app/src/main/java/com/matxowy/flashcardsapp/data/db/FlashcardsDatabase.kt
> +            applicationScope.launch {
Pewnie zwykłe `runBlocking{` by tu wystarczyło.

2023-03-13 17:04 UTC, msniezek-Sii commented on app/src/main/java/com/matxowy/flashcardsapp/presentation/learning/view/LearningScreenFragment.kt
> +                btnPrevious.isVisible = viewState.isLoading.not()
Nie ma sensu chować każdego elementu osobno. Lepiej jest zebrać je wszystkie w jednym kontenerze (jakiś layout, LinearLayout, ConstraintLayout etc) i sterować widocznością całego kontenera. Tak jak to zrobiłeś teraz jest niepraktycznie, zwłaszcza jak jest dużo elementów do dodania/ukrycia. Bardzo łatwo wtedy o jakiś błąd, coś się nie ukryje albo nie pojawi kiedy powinno i trudno to zauważyć.

2023-03-13 17:04 UTC, msniezek-Sii commented on app/src/main/java/com/matxowy/flashcardsapp/presentation/learning/view/LearningScreenFragment.kt
> +                mtvFlashcardBack.text = viewState.flashcards.getOrNull(FIRST_FLASHCARD_INDEX)?.backText ?: EMPTY_STRING
Nie rozumiem idei przekazywania całej listy fiszek. ViewState powinien zawierać aktualny stan ekranu i tylko tyle. Wyświetlamy na raz tylko jedną fiszkę więc nie ma powodu, żeby viewState trzymał je wszystkie.

2023-03-13 17:04 UTC, msniezek-Sii commented on app/src/main/java/com/matxowy/flashcardsapp/presentation/learning/viewmodel/LearningScreenViewModel.kt
> +        _viewState.update { it.copy(isLoading = false, categoryName = categoryName, flashcards = flashcardsList) }
Tak jak pisałem w komentarzu do fragmentu, nie ma powodu, żeby viewState trzymał całą listę fiszek. Powinien trzymać tylko obecnie wyświetlaną. A co do tego jak je wyciągać z bazy to tu są dwa podejścia:
1. dodajesz sobie prywatne pole do ViewModel, które trzyma wszystkie wyciągnięte fiszki, żeby nie robić zapytania do bazy po jednej fiszce.
2. przy każdej zmianie fiszki robisz zapytanie do bazy i wyciągasz je po jednej na raz.
Myślę, że w tym przypadku pierwsze podejście będzie ok ;)

2023-03-13 17:04 UTC, msniezek-Sii commented on app/src/main/java/com/matxowy/flashcardsapp/presentation/main/view/MainScreenFragment.kt
> +        val namesOfTheCategories = viewModel.getNamesOfTheCategories(listOfCategories)
To jest bardzo brzydkie i wbrew MVVM. Tak się nie robi :) W sensie MVVM realizuje observer pattern, czyli nie powinno być bezpośredniego połączenia z ViewModel do View. View każe zrobić coś ViewModelowi i obserwuje viewModel czekając na wynik. Robiąc tak jak zrobiłeś to proszenie się o problemy, można sobie przypadkiem zablokować UI, jeśli metoda, którą wołasz będzie się długo wykonywała.
W tym przypadku jest kilka opcji:
1. nadpisujesz metodę `toString` obiektu Category tak, żeby zwracała `Category.name` i można wrzucić listę prosto do adaptera.
2. robisz własną wersję adaptera (własny ArrayAdapter), który przyjmuje listę obiektów Category i wyciąga sobie nazwę z odpowiedniego pola a nie korzysta z `toString` obiektu
3. Robisz sobie nową data klasę, jakieś `CategorySpinnerItem` z polami `name, `categoryId` i w tym obiekcie nadpisujesz `toString` (żeby nie mieszać w Category) w z viewModel zwracasz w ViewState listę tych nowych obiektów i ładujesz ją do adaptera
Możesz wybrać jak wolisz to rozwiązać, dla mnie obojętne :)

2023-03-13 17:04 UTC, msniezek-Sii commented on app/src/main/java/com/matxowy/flashcardsapp/presentation/main/viewmodel/MainScreenViewModel.kt
> +    fun getNamesOfTheCategories(listOfCategories: List<Category>) = listOfCategories.map { category -> category.name }
viewModel powinien wystawiać tylko Akcę i ViewState, nie zwracamy danych bezpośrednio.

2023-03-14 14:45 UTC, matxowy commented on app/src/main/java/com/matxowy/flashcardsapp/data/db/FlashcardsDatabase.kt
> +            applicationScope.launch {
Próbowałem z runBlocking, ale niestety nie działało więc zostawiłem tak jak było

2023-03-14 14:46 UTC, matxowy commented on app/src/main/java/com/matxowy/flashcardsapp/presentation/learning/view/LearningScreenFragment.kt
> +                btnPrevious.isVisible = viewState.isLoading.not()
Racja! Dodawałem to chowanie na sam koniec tego taska i już nie pomyślałem o tym żeby to załadować w jeden kontener, ale już poprawione ☺️

2023-03-14 14:46 UTC, matxowy commented on app/src/main/java/com/matxowy/flashcardsapp/presentation/learning/view/LearningScreenFragment.kt
> +                mtvFlashcardBack.text = viewState.flashcards.getOrNull(FIRST_FLASHCARD_INDEX)?.backText ?: EMPTY_STRING
Dobra uwaga, poprawione 😄

2023-03-14 14:47 UTC, matxowy commented on app/src/main/java/com/matxowy/flashcardsapp/presentation/learning/viewmodel/LearningScreenViewModel.kt
> +        _viewState.update { it.copy(isLoading = false, categoryName = categoryName, flashcards = flashcardsList) }
Zrobiłem pierwsze podejście ☺️

2023-03-14 14:50 UTC, matxowy commented on app/src/main/java/com/matxowy/flashcardsapp/presentation/main/view/MainScreenFragment.kt
> +        val namesOfTheCategories = viewModel.getNamesOfTheCategories(listOfCategories)
Totalnie nie pomyślałem o tym przy pisaniu, ale teraz widzę, że to było bez sensu. Poprawione, nadpisałem metodkę toString w obiekcie Category ☺️

2023-03-14 14:50 UTC, matxowy commented on app/src/main/java/com/matxowy/flashcardsapp/presentation/main/viewmodel/MainScreenViewModel.kt
> +    fun getNamesOfTheCategories(listOfCategories: List<Category>) = listOfCategories.map { category -> category.name }
O dobrze wiedzieć! Poprawione 😄

2023-03-15 10:22 UTC, merged